spring.application.name=Ecommerce-application

<<<<<<< HEAD
server.port=${PORT:5454}
=======
# Render assigns PORT automatically
server.port=${PORT:5454}


# DATABASE (MySQL)
>>>>>>> 48fa042 (Fix Nullable import and update config)

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

<<<<<<< HEAD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======
>>>>>>> 48fa042 (Fix Nullable import and update config)

# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

<<<<<<< HEAD
razorpay.api.key=${RAZORPAY_KEY}
razorpay.api.secret=${RAZORPAY_SECRET}
jwt.secret=${JWT_SECRET}
=======

# RAZORPAY

razorpay.api.key=${RAZORPAY_KEY}
razorpay.api.secret=${RAZORPAY_SECRET}
>>>>>>> 48fa042 (Fix Nullable import and update config)
